### ISSUE TITLE
How to configure two segments

### ISSUE THREAD

**Issue by sayseee** [siddhartha-gupta/ionic-3-swipe-able-segments#2]
Hello,

The code works perfectly with 3 segments however there seems to be a problem when handling two segments. The swipe gesture has to be done like 3 or four times for it to work,

How does one go about with this?

thx

**Comment by siddhartha-gupta** [comment]
The code is in develop branch for now. You can check the code in here - https://github.com/siddhartha-gupta/ionic-3-swipe-able-segments/tree/develop/src/pages/multiple-tabs

For 2, 3, n tabs, it worked fine for me. Let me know in case you face any further issues.
